/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef APP_H
#define APP_H

#include <string>

//namespace is that of the project
namespace attack {
    class Greeter {
        public:
        std::string userinput(std::string s);
        double AttackerSuccessProbability(double q, int z);
    };
}

#endif
